global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "lawhelp_rules.yml"

scrape_configs:
  - job_name: 'lawhelp-application'
    static_configs:
      - targets: ['localhost:5000']
    metrics_path: '/api/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['localhost:9104']
    scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Sample alerting rules
rule_files:
  - "alert_rules.yml"